name: Merge Dependabot PRs

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge Dependabot PRs
        run: |
          for pr in $(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/asp-dotnet-app-github-action-pipeline/sumanprasad007/asp-dotnet-app-github-action-pipeline/pulls\?state\=open\&head\=dependabot | jq -r '.[].number'); do
            curl -s - "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -X PUT https://api.github.com/asp-dotnet-app-github-action-pipeline/sumanprasad007/asp-dotnet-app-github-action-pipeline/pulls/$pr/merge
          done
