name: Merge Pull Requests

on:
  # schedule:
  #   - cron: '0 0 * * *' # every day at midnight

  push:
    branches: [ "main" ]

jobs:
  merge-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge pull requests
        run: |
          for pr in $(curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" https://api.github.com/repos/sumanprasad007/asp-dotnet-app-github-action-pipeline/pulls\?state\=open\&head\=dependabot | jq -r '.[] | .number'); do
            curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -X PUT https://api.github.com/repos/sumanprasad007/asp-dotnet-app-github-action-pipeline/pulls/$pr/merge
          done
