name: Secret Scanning

on:
  push:
    branches: [ "main" ]

jobs:
  scan-secrets:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install truffleHog
      run: |
        curl -L https://github.com/dxa4481/truffleHog/releases/download/v2.1.0/truffleHog_windows_amd64.exe -o truffleHog.exe
        chmod +x truffleHog.exe
    - name: Scan for secrets
      run: |
        ./truffleHog.exe --entropy=False --regex .
